---
title: "Brainstorming Ideas"
---

## Notes from First Meeting
As mentioned in the meeting, we will set up another meeting (off-schedule) to dive further into the ideas we settled on. Each idea was assigned to someone who will distribute the 1 page proposal prior to our next meeting for comments/suggestions. Then at the next session we will do a brainstorming break-out exercise to settle on (1) which ideas to pursue, (2) what the structure of the project looks like, and (3) assign division of work. 

The topics were assigned to: 
Nfamara: Nature based solutions for cooling
Steve: Global differences in ecosystem value under different reforms and different scenarios
Adriana: Water quality, access, and poverty in the USA
Saleh: Coastal erosion, housing, and nature-based solutions to natural disasters.
Below are notes on the topics from our meeting that were written on the board. 

Nfamara: Nature based solutions for cooling
Developed vs developing settings
biodiversity as cooling in urban areas
Saving and energy costs for wealthy vs. health costs for poor.
Similar to work by world bank in India
Nature based solutions (Invest) to consider ecological relationships before application of policies
Steve: Global differences in ecosystem value under different reforms and different scenarios
Similar to Invest-GTAP. Fits in NatCap portfolio
Evaluate GDP and GEP
Economic analysis of ecosystem services and distribution
Benefit is can produce many side projects
Adriana: Water quality, access, and poverty in the USA
Safe water act and the quality of water
Replacement of lead pipes and addressing forever chemicals (PFAS)
Inequality in use of recreational water (swimming, lakes, etc.)
Saleh: Coastal erosion, housing, and nature-based solutions to natural disasters.
Water rise and vulnerability of housing
Previous work had issues with DEM and mapping this to housing
Similar to work done at UC Santa Cruz
What is odd is that prices are rising in coastal areas vulnerable to consistent natural disasters. Why take the risky investments?
Potentially a way of seeing how individuals rationalize risk when a loss is inevitable (p/m a couple of years).
Perhaps willingness to relocate/migrate is determined by loss of property value's future growth (wealthy) or limited resources to move (poor)
The scarcity of coastal housing due to continued natural disasters may increase the NPV (risk makes it MORE valuable)
Could be analyzed in similar fashion as hedonic models or willingness to pay.
Perhaps there are nature-based solutions to coastal erosion (mangroves) that can help with opportunity cost.

 